version: 2

jobs:
  lib:
    working_directory: ~/redux-saga-firebase

    docker:
      - image: node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - rsf-{{ .Branch }}-{{ checksum "package.json" }}
            - rsf-{{ .Branch }}
            - rsf-master-{{ checksum "package.json" }}
            - rsf-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test -- --coverage

      - run:
          name: Install coveralls
          command: yarn global add coveralls

      - run:
          name: Send coverage to coveralls.io
          command: |
            if [ -z "$CIRCLE_PR_REPONAME" ];
            then
              cat coverage/lcov.info | coveralls;
            fi

      - save_cache:
          key: rsf-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/redux-saga-firebase/node_modules

  demo:
    working_directory: ~/redux-saga-firebase

    docker:
      - image: node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - demo-{{ .Branch }}-{{ checksum "example/package.json" }}
            - demo-{{ .Branch }}
            - demo-master-{{ checksum "example/package.json" }}
            - demo-master

      - run:
          name: Install dependencies
          command: cd example && yarn

      - run:
          name: Run tests
          command: cd example && yarn test

      - save_cache:
          key: demo-{{ .Branch }}-{{ checksum "example/package.json" }}
          paths:
            - ~/.yarn
            - ~/redux-saga-firebase/example/node_modules

workflows:
  version: 2
  stack:
    jobs:
      - lib
      - demo
