version: 2

jobs:
  build:
    working_directory: ~/redux-saga-firebase

    docker:
      - image: node:7

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test -- --coverage

      - run:
          name: Install coveralls
          command: yarn global add coveralls

      - run:
          name: Send coverage to coveralls.io
          command: cat coverage/lcov.info | coveralls

      - save_cache:
          key: yarn
          paths:
            - ~/.yarn
