version: 2

jobs:
  build:
    working_directory: ~/redux-saga-firebase

    docker:
      - image: node:7

    steps:
      - checkout

      - restore_cache:
          keys:
            - rsf-{{ .Branch }}-{{ checksum "package.json" }}
            - rsf-{{ .Branch }}
            - rsf-master-{{ checksum "package.json" }}
            - rsf-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Check yarn.lock is up to date
          command: yarn check

      - run:
          name: Run tests
          command: yarn test -- --coverage

      - run:
          name: Install coveralls
          command: yarn global add coveralls

      - run:
          name: Send coverage to coveralls.io
          command: |
            if [ -z "$CIRCLE_PR_REPONAME" ];
            then
              cat coverage/lcov.info | coveralls;
            fi

      - save_cache:
          key: rsf-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/redux-saga-firebase/node_modules
